### PR TITLE
Support pre-releases in release tooling

### PR DESCRIPTION
**Pull request by alcaeus**
This adds support for pre-releases in the release tooling. For now, this considers only alpha and beta versions, but release candidates can be added as well.

Differences between stable releases and pre-releases:
* For pre-releases, the GitHub Release is marked as such
* For pre-releases, the version in build.gradle is set back to a snapshot of said version, e.g. 5.3.0-beta1 => 5.3.0-snapshot

Branch checks are run on the version without pre-release markers, so a pre-release for a patch release can only be created from the corresponding maintenance branch. At the same time, pre-release versions of non-patch releases can be created from the master branch, and the tooling will create the maintenance branch.

Link to a run: https://github.com/alcaeus/mongo-java-driver/actions/runs/9596715534

JAVA-5506

### CODE REVIEW

**Comment by alcaeus** [comment]
After discussing with @jyemin, I've made a few changes to the release process:

1. The version currently present in `build.gradle` is checked before releasing. When releasing a version `A.B.C(-suffix)?`, we're looking for a `A.B.C-SNAPSHOT` version in `build.gradle` - if that doesn't exist the release does not go ahead
2. Patch releases can only be made from the corresponding maintenance branch. This could technically be removed if we assume that the version in `build.gradle` is always up-to-date, but the added check doesn't hurt
3. Non-Patch releases (e.g. 5.2.0 or 6.0.0) including its pre-releases can be made from the master branch as well. For pre-releases, no maintenance is created, but when releasing a stable version a maintenance branch is created
4. Release candidates are now also supported using the `rc` suffix.

Here's a table that illustrates a whole chain of pre-releases and a stable release:
| Version | Workflow Run | Version bump | Post-release version bump |
|--------|--------|--------|--------|
| [5.2.0-alpha0](https://github.com/alcaeus/mongo-java-driver/releases/tag/r5.2.0-alpha0) | [Link](https://github.com/alcaeus/mongo-java-driver/actions/runs/9613007628) | https://github.com/alcaeus/mongo-java-driver/commit/585f35c20843d34569a39522c8e82436dd628d77 | https://github.com/alcaeus/mongo-java-driver/commit/b513160780220a428e95cd73f7f9a495904909bf |
| [5.2.0-beta0](https://github.com/alcaeus/mongo-java-driver/releases/tag/r5.2.0-beta0) | [Link](https://github.com/alcaeus/mongo-java-driver/actions/runs/9613017379) | https://github.com/alcaeus/mongo-java-driver/commit/f8b6c2babcd3c86126fa7aba99315174f4feb09a | https://github.com/alcaeus/mongo-java-driver/commit/534f0398ab81bb297f0fa5e6598fd44e66c51efe |
| [5.2.0-beta1](https://github.com/alcaeus/mongo-java-driver/releases/tag/r5.2.0-beta1) | [Link](https://github.com/alcaeus/mongo-java-driver/actions/runs/9613023620) | https://github.com/alcaeus/mongo-java-driver/commit/461f48f01de3b8258326e596bf0cad096d796e23 | https://github.com/alcaeus/mongo-java-driver/commit/c9373d7b5261aa537809279bf6cee8e231d4f17e |
| [5.2.0-rc0](https://github.com/alcaeus/mongo-java-driver/releases/tag/r5.2.0-rc0) | [Link](https://github.com/alcaeus/mongo-java-driver/actions/runs/9613032653) | https://github.com/alcaeus/mongo-java-driver/commit/b0a2c12b46c06488fe4b3001cc488316d01be0e0 | https://github.com/alcaeus/mongo-java-driver/commit/3dad9d7307b9fe062d371218d60a128ecb701be0 |
| [5.2.0](https://github.com/alcaeus/mongo-java-driver/releases/tag/r5.2.0) | [Link](https://github.com/alcaeus/mongo-java-driver/actions/runs/9613043615) | https://github.com/alcaeus/mongo-java-driver/commit/d0cc8e844bd429db65424ae9aa56f113ebd2b0f8 | https://github.com/alcaeus/mongo-java-driver/commit/682254a7ea902e2b481dcf7189be524c87061151 |

As a stable non-patch release, the last release is a bit special and the commit links diverge. The bump commits for 5.2.0 were made in the 5.2.x branch, with master being bumped to 5.3.0-SNAPSHOT in https://github.com/alcaeus/mongo-java-driver/commit/4961f18dfdafe91127e6c04a9be682dd2ef37b45. This gives a good history in both [master](https://github.com/alcaeus/mongo-java-driver/commits/4961f18dfdafe91127e6c04a9be682dd2ef37b45) and [5.2.x](https://github.com/alcaeus/mongo-java-driver/commits/682254a7ea902e2b481dcf7189be524c87061151) branches.

**Review by jyemin — COMMENTED** [review]
LGTM, but one question for the group:

As a best practice, should we always branch on creation of rc0?

**Comment by stIncMale** [comment]
> As a best practice, should we always branch on creation of rc0?

@jyemin Could you please clarify the question? My understanding is that you are referring to the _"For pre-releases, no maintenance is created"_ behavior, and want the `rc0` pre-release to be different in a way that it results in a maintenance branch creation. But that would also mean that any pre-releases following `rc0` would have to be created from that maintenance branch. Such a split in the logic of pre-releases would only complicate the workflow. But maybe I misunderstand the whole thing.

Why do you think we should treat `rc0` differently from other pre-releases?

**Comment by jyemin** [comment]
@alcaeus pointed out to me in a 1:1 that my question really applies to betas as well as rcs.  The argument is that both betas and rcs are intended to be feature complete releases, just with varying level of quality and stability guarantees as a GA release.  By branching on first beta or rc, it opens up the main branch for commits of new features.

**Comment by stIncMale** [comment]
> my question really applies to betas as well as rcs

If the proposal is to create a maintenance branch for all kinds of pre-releases, then sure, let's do that. However, that would mean we need to bump up the version in the `master`, similarly to how we do that when creating a maintenance branch for a minor or a major release.

**Review by rozza — APPROVED** [review]
LGTM

**Review by jyemin — APPROVED** [review]
LGTM

**Comment by stIncMale** [comment]
Pushed a commit (merge `master` to `alcaeus:support-pre-releases` https://github.com/mongodb/mongo-java-driver/pull/1425/commits/b32f92b3f0b588196f03a66c963fe2729d6ba785) to resolve merge conflicts.

**Pull request merged**
