### PR TITLE
Validate RewrapManyDataKeyOptions

### PR DESCRIPTION
**Pull request by rozza**
Ensure that the provider exists if a master key has been provided.

JAVA-4717

### CODE REVIEW

**Review by jyemin — APPROVED** [review]
LGTM, added Kevin as a reviewer.

**Review by kevinAlbs — APPROVED** [review]
LGTM. C has the same bug, and possibly Go. Filed https://jira.mongodb.org/browse/DRIVERS-2441 in case this impacts other drivers.

**Comment by jyemin** [comment]
@rozza can this be merged (and also cherry picked to the main branch)?

**Comment by rozza** [comment]
Merged and on master as well.

**Pull request merged**
