### PR TITLE
Allow a custom encoder to use when performing a find query

### PR DESCRIPTION
**Pull request by romario13**

### CODE REVIEW

**Comment by jyemin** [comment]
Can you add a test to show what you're trying to achieve here?

**Comment by romario13** [comment]
The reason for this is to use the encoder to insert operation.  At the insert operation driver accept custom encoder. DBObject query may contain custom DBObject on the tree and I prefer to control their BSON serialization stream to achieve the best performance.

For example. I can put custom object into update operation:

```java
DBObjectCheat documentKey = new DBObjectCheat(key);
                DBObjectCheat document = new DBObjectCheat(value);
                coll.update(documentKey, document, true, false);
```

Then i can catch documentKey object at custom encoder

```java
        if (!(o instanceof DBObjectCheat)) {
            return false;
        }

        Object obj = ((DBObjectCheat) o).getObject();
        if (obj == null) {
            throw new IllegalArgumentException("DBObjectCheathas no (null) object to encode");
        }

        StreamBSerializer streamBSerializer = bSerializationService.getSerializer(obj.getClass());

        final int sizePos = _buf.getPosition();
        _buf.writeInt(0); // leaving space for this.  set it at the end

        streamBSerializer.write(this, obj);

        _buf.write(EOO);
        _buf.writeInt(sizePos, _buf.getPosition() - sizePos);

        return true;
```

And then use fastest serializer for particular object

```java
public class RootPojoStreamBSerializer implements StreamBSerializer<RootPojo> {

    public static final CString I = new CString("i");
    public static final CString STR = new CString("str");
    public static final CString DATE = new CString("date");
    public static final CString UUID = new CString("uuid");
    public static final CString HOUSE = new CString("house");
    public static final CString LONG_ARRAY = new CString("longArray");

    InnerPojoStreamBSerializer innerSerializer = new InnerPojoStreamBSerializer();

    @Override
    public Class<RootPojo> getObjectClass() {
        return RootPojo.class;
    }

    @Override
    public void write(BDataOutput out, RootPojo rootObj) {

        out.writeInt(_ID, rootObj.getI());
        out.writeString(STR, rootObj.getStr());
        out.writeDate(DATE, rootObj.getDate());
        out.writeUUID(UUID, rootObj.getUuid());

        InnerPojo house = rootObj.getHouse();

        if (house != null) {
            final int label = out.writeObject(HOUSE);
            innerSerializer.write(out, rootObj.getHouse());
            out.writeObjectStop(label);
        }

        long[] longs = rootObj.getLongArray();

        if (longs != null) {
            final int label = out.writeArray(LONG_ARRAY);
            for (int i = 0; i < longs.length; i++) {
                out.writeLong(i, longs[i]);
            }
            out.writeArrayStop(label);
        }

    }

    @Override
    public RootPojo read(BDataInput in) {

        RootPojo obj = new RootPojo();
        obj.setI(in.readInt(_ID));

        obj.setDate(in.readDate(DATE));

        int label = in.readObject(HOUSE);
        if (label != -1) {
            obj.setHouse(innerSerializer.read(in));
            in.readObjectStop(label);
        }

        obj.setUuid(in.readUUID(UUID));

        label = in.readArray(LONG_ARRAY);
        if (label != -1) {
            int arraySize = in.readArraySize();
            long[] longs = new long[arraySize];

            for (int i = 0; i < arraySize; i++) {
                longs[i] = in.readLong(i);
            }

            obj.setLongArray(longs);

            in.readArrayStop(label);
        }

        obj.setStr(in.readString(STR));

        return obj;
    }
}
```

The mine goal s to give the opportunity to avoid costly conversion to POJO DBObject map structure and vice versa. I can do this on simple queries, but can not when try to request an update of a particular object.

**Comment by romario13** [comment]
This is an example of plugin to mongo driver
https://github.com/taskurotta/taskurotta/tree/develop/mongodb/src/main/java/ru/taskurotta/mongodb/driver
There is a perfomence test:
https://github.com/taskurotta/taskurotta/blob/develop/hazelcast/src/test/java/ru/taskurotta/mongodb/driver/MongoSerializationTest.java

Sometimes plugin forced to use deprecated driver API.Please do not pay attention to it We are waiting the third version of driver to avoid this.

**Comment by tkgreg** [comment]
Also you could check our compare test with custom serialization to BSON https://github.com/taskurotta/taskurotta/blob/develop/services-hz/src/test/java/ru/taskurotta/hz/test/SerializationCompareTest.java

*FYI: Test measures only stage of serialization without real write-read operation to mongo*

**Test Results**

*Our custom serialization for MongoDB driver*
BSON: Serialization took **680 ms**, object size 1354 bytes
BSON: Deserialization took **1580 ms** object size 1350 bytes

*Default serialization by MongoDB driver*
DBObject: Serialization took **8158 ms**, object size 1350 bytes
DBObject: Deserialization took **16969 ms**, object size 1678 bytes

*Custom serialization to Hazelcast*
HZ: Serialization took 459 ms, object size 792 bytes
HZ: Deserialization took 672 ms object size 792 bytes

**Comment by jyemin** [comment]
Thanks for providing the extensive context.  Can you open an issue in Jira that we can link this to as well as add a test case?

**Comment by tkgreg** [comment]
I have created this one https://jira.mongodb.org/browse/JAVA-1647
What kind of test case do you want to see? As you see above we have already provided our test.

**Comment by rozza** [comment]
Hi @tkgreg the test case should be submitted as part of the pull request - this way we can see intent, keep the test coverage up and ensure there is a regression test as part of the codebase.

**Comment by rozza** [comment]
I'm closing this pull request, as the related jira ticket has been closed as "fixed" - thanks to the changes in  the 3.0. series.

**Pull request closed without merging**
