### PR TITLE
JAVA-3684: deprecate geohaystack

### PR DESCRIPTION
**Pull request by terakilobyte**
This removes mention of geoHaystack from the docs and marks methods as deprecated.

### CODE REVIEW

**Review by rozza — CHANGES_REQUESTED** [review]
Looks good, only one thing, where methods are deprecated you should also add the `@deprecated` tag and message in the java docs

**Comment by terakilobyte** [comment]
I thought I had added the @deprecated tags. Do you mean to add a quick note within the method docs it is deprecated and what to use instead?

**Comment by rozza** [comment]
@terakilobyte - here's an example: https://github.com/mongodb/mongo-java-driver/blob/8574c6daff4b8a1ecf65c67a301287bc919b5b7c/driver-core/src/main/com/mongodb/event/ConnectionPoolListener.java#L133-L138

**Comment by terakilobyte** [comment]
I've added to the method docs for the public facing methods. I was unsure if it needed to be done for the methods in internal based on driver policy.

**Comment by rozza** [comment]
@terakilobyte unfortunately you have to double annotate with Java once for thing being deprecated and then again in the javadoc.  Scala is nicer as the annotation is combined.

I've updated the java docs and will squash and merge.

Many thanks

**Pull request merged**
