### PR TITLE
Docs - fix headers and menu toggle

### PR DESCRIPTION
**Pull request by rozza**
JAVA-1865

Can test here: http://rozza.github.io/mongo-java-driver/3.1/driver/reference  (cmd+r to hard refresh the js).

[Review on Reviewable](https://reviewable.io/reviews/mongodb/mongo-java-driver/328)

### CODE REVIEW

**Comment by jyemin** [comment]
lgtm

**Comment by jyemin** [comment]
Actually, I

**Comment by rozza** [comment]
I'll add some window resize logic - its not going to be indicative of a mobile experience as they wont be able to resize past the set minimum.

**Comment by rozza** [comment]
Should be better now - will need to hard refresh to get the latest script.

**Comment by jyemin** [comment]
What behavioral difference should I see now?

**Comment by rozza** [comment]
The difference should be that the menu toggle works on small screens.

**Comment by jyemin** [comment]
lgtm

**Comment by rozza** [comment]
Rebased and merged

**Pull request closed without merging**
