### PR TITLE
Change slaveOk to secondaryOk and isMaster to hello

### PR DESCRIPTION
**Pull request by jyemin**
JAVA-4159

### CODE REVIEW

**Review by rozza — CHANGES_REQUESTED** [review]
Added some extra changes in  https://github.com/rozza/mongo-java-driver/tree/j4159

See:  rozza@83d4d99
See:  rozza@284e83a

**Comment by jyemin** [comment]
Those changes look good to me.  Can you add them to the PR?

**Review by rozza — APPROVED** [review]

**Comment by rozza** [comment]
Done!

**Comment by jyemin** [comment]
@rozza added one more commit.  PTAL.

**Review by rozza — APPROVED** [review]
Good catch - LGTM

**Pull request merged**
