### PR TITLE
Iteration should throw if cursor is closed

### PR DESCRIPTION
**Pull request by jyemin**
This changes the behavior of the cursor implementations in the CRUD API
such that attempts to iterate the cursor with hasNext/next/tryNext will
throw IllegalStateException instead of returning already-cached results
from previous iteration.

JAVA-4368

### CODE REVIEW

**Comment by stIncMale** [comment]
`MongoChangeStreamCursorImpl` and `MongoBatchCursorAdapter` both implement `MongoCursor`. `MongoCursor.close` may be called concurrently with other methods of `MongoCursor`, even though `MongoCursor` is not thread-safe. See [`MongoCursor.close`](https://mongodb.github.io/mongo-java-driver/4.4/apidocs/mongodb-driver-sync/com/mongodb/client/MongoCursor.html#close()). This is currently not taken into account in the PR changes.

**Comment by jyemin** [comment]
What do you suggest?  Does it require that all iteration methods become synchronized?

**Review by stIncMale — CHANGES_REQUESTED** [review]
`MongoChangeStreamCursorImpl` and `MongoBatchCursorAdapter` both implement `MongoCursor`. `MongoCursor.close` may be called concurrently with other methods of `MongoCursor`, even though `MongoCursor` is not thread-safe. See [`MongoCursor.close`](https://mongodb.github.io/mongo-java-driver/4.4/apidocs/mongodb-driver-sync/com/mongodb/client/MongoCursor.html#close()). This is currently not taken into account in the PR changes.

**Comment by stIncMale** [comment]
> What do you suggest? Does it require that all iteration methods become synchronized?

The requirement adds noticeable burden to not otherwise thread-safe code. Serializing executions of all methods that access state accessed by `close`, is the most straightforward approach. We can use `synchronized` with a `private` object, or `StampedLock.asWriteLock()`.

**Comment by jyemin** [comment]
Decided not to merge.  The problem is that `close()` is allowed to be called concurrently with iteration methods, which requires at minimum that `isClosed` be volatile.  There is some cost to that, and it's not clear that it's worth the benefit that we get from throwing while iterating a closed cursor, given how rare that should be in practice.

**Pull request closed without merging**
