### PR TITLE
Deprecate timeout options.

### PR DESCRIPTION
**Pull request by vbabanin**
JAVA-5290

### CODE REVIEW

**Review by rozza — CHANGES_REQUESTED** [review]
Looking good.

Couple of things: 
 * Scaladoc formatting seems off (extra spacing)
 * Run: `./gradlew clean check --continue -xtest -xintegrationTest` and see if you can suppress some of the deprecation warnings.

**Comment by rozza** [comment]
I added JAVA-5373 to ensure MongoClient gets added to the doc examples, to not delay this or the other PR.

**Review by rozza — APPROVED** [review]
I found some warnings - so rather than potentially delaying the merge I fixed up and pushed to your branch.

Also deprecated `dropIndexOptions.maxTime` and preferred using `@Suppress("DEPRECATION")` on methods as opposed to being inline - doesn't hinder readability.

LGTM - but please make sure you're happy with my commit.

**Comment by vbabanin** [comment]
Thanks for the fixes and handling the deprecation warnings @rozza! LGTM!

**Pull request merged**
