### PR TITLE
Update the legacy uber packages pom.xml

### PR DESCRIPTION
**Pull request by rozza**
Update the name and description to indicate these are legacy and not the most recent release.

JAVA-4854

### CODE REVIEW

**Review by jyemin — COMMENTED** [review]
Should we do the same for async (and suggest reactive streams)?

**Comment by rozza** [comment]
@jyemin good idea - also update embedded description as well.

**Review by jyemin — COMMENTED** [review]
I have some concern that this will cause a different confusion for users.  If they are using mongo-java-driver or mongodb-driver with the legacy API (com.mongodb.MongoClient), and they just switch to mongodb-driver-sync, they will be confused because what they really need is mongodb-driver-legacy.  What do you think about mentioning that artifact as well?

CC @ashni-mongodb

**Comment by rozza** [comment]
Its a tricky one - saying this is a legacy driver and then suggesting another legacy driver might also be confusing :(

**Comment by jyemin** [comment]
Maybe we shouldn't call the 3.x driver legacy?

**Comment by ashni-mongodb** [comment]
Hmm agreed that there might be confusion marking this as legacy. What if we call it unsupported or unmaintained so that we can retain the "legacy" language for the "mongodb-driver-legacy" artifact?

Something like this, maybe?

"This driver is no longer maintained / updated by MongoDB. For the most up-to-date version of the Java Driver, please see mongodb-driver-sync. To use the legacy API, please refer to mongodb-driver-legacy."

**Comment by jyemin** [comment]
Maybe "this artifact" instead of "this driver".  And use the work artifact as a suffix for all the names, so it's clear what we're talking about.

**Review by jyemin — APPROVED** [review]
That looks good.  Ship it!

**Review by katcharov — APPROVED** [review]

**Pull request merged**
