### PR TITLE
Add getString/getLong/getDouble with default value to Document

### PR DESCRIPTION
**Pull request by slothspot**

### CODE REVIEW

**Comment by slothspot** [comment]
Hi @rozza , added tests for added methods.

**Comment by slothspot** [comment]
@rozza Any update on this one?

**Comment by rozza** [comment]
@slothspot - this looks good. Will review and look to merge next week.

**Comment by rozza** [comment]
Hi @slothspot thanks again for this PR. 

During the code review phase, the JVM team thought it would be even cleaner to just add:

    Document.get('key', defaultValue)

Its analogous to the `Map.getOrDefault` that was added in Java 8, works for all possible types, keeps the API simple and works well in Java 6 & 7.

This improvement will be released in 3.5!

**Pull request closed without merging**
